--
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Track Everything
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #  https://www.curseforge.com/wow/addons/track-everything/localization   #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--

local _, ADDON_TABLE = ...
local ADDON_NAME = ADDON_TABLE.ADDON_NAME

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "enUS", true, true)

  if L then
    L[" Spell switching: %s, Last tracked upon ressurection: %s. Type %s to see all chat commands. Have a nice day! :)"] = true
    L["%sDrag%s to move icon"] = true
    L["%sLeft-click%s to manualy select tracking spell"] = true
    L["%sRight-click%s to cancel current tracking spell"] = true
    L["%sShift+Left-click%s to enable/disable auto switching"] = true
    L["%sShift+Right-click%s to open settings"] = true
    L["Activate last used tracking spell on resurrection"] = true
    L["Arguments to %s :"] = true
    L["Auto spell switching"] = true
    L["Auto tracking"] = true
    L["Cast interval"] = true
    L["Check if you want to hide default minimap tracking icon"] = true
    L["Check to hide addon minimap icon"] = true
    L["Check to show required profession level on minimap tooltips"] = true
    L["Check to show required profession level on world map tooltips. Requires GatherMate2 addon."] = true
    L["Check to show required profession level on world object tooltips"] = true
    L["Copper Vein"] = true
    L["Current tracking spell"] = true
    L["Dark Iron Deposit"] = true
    L["Disable auto spell switching"] = true
    L["Enable auto spell switching"] = true
    L["Enable to activate last used tracking spell on resurrection"] = true
    L["Enable to switch only while character is moving"] = true
    L["Enable/disable auto spell switching"] = true
    L["Enable/disable last used tracking spell activation on resurrection"] = true
    L["Enable/disable required profession level on Minimap tooltips"] = true
    L["Enable/disable required profession level on World Map tooltips"] = true
    L["Enable/disable required profession level on World tooltips"] = true
    L["Enable/disable spell switching only while moving mode"] = true
    L["Force in combat"] = true
    L["Gold Vein"] = true
    L["Hakkari Thorium Vein"] = true
    L["Herbalism"] = true
    L["Hide addon icon"] = true
    L["Hide default tracking icon"] = true
    L["Icon display mode"] = true
    L["Incendicite Mineral Vein"] = true
    L["Indurium Mineral Vein"] = true
    L["Iron Deposit"] = true
    L["Large Obsidian Chunk"] = true
    L["Last used tracking spell activation is [%s]"] = true
    L["Lesser Bloodstone Deposit"] = true
    L["Minimap tooltips"] = true
    L["Mining"] = true
    L["Mithril Deposit"] = true
    L["Mute spell use sound"] = true
    L["Mute spell use sound is [%s]"] = true
    L["Mute spell use sound while auto tracking"] = true
    L["Next tracking spell"] = true
    L["Only while moving"] = true
    L["Ooze Covered Gold Vein"] = true
    L["Ooze Covered Iron Deposit"] = true
    L["Ooze Covered Mithril Deposit"] = true
    L["Ooze Covered Rich Thorium Vein"] = true
    L["Ooze Covered Silver Vein"] = true
    L["Ooze Covered Thorium Vein"] = true
    L["Ooze Covered Truesilver Deposit"] = true
    L["Open settings"] = true
    L["Print information about Author"] = true
    L["Required profession level on Minimap tooltips is [%s]"] = true
    L["Required profession level on World Map tooltips sis [%s]"] = true
    L["Required profession level on World tooltips is [%s]"] = true
    L["Resources"] = true
    L["Rich Thorium Vein"] = true
    L["Select to include in auto switching"] = true
    L["Select what to display inside icon"] = true
    L["Settings have been reset to default"] = true
    L["Show required profession level"] = true
    L["Silver Vein"] = true
    L["Small Obsidian Chunk"] = true
    L["Small Thorium Vein"] = true
    L["Spell switching is [%s]"] = true
    L["Spell switching only while moving is [%s]"] = true
    L["Switch spells even if player in combat"] = true
    L["Time in seconds between spell casts while auto switching"] = true
    L["Tin Vein"] = true
    L["Toggle auto spell switching"] = true
    L["Tooltip"] = true
    L["Tracking spells"] = true
    L["Truesilver Deposit"] = true
    L["Units"] = true
    L["World Map tooltips"] = true
    L["World tooltips"] = true
    L["Current tracking"] = true
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "frFR");
  
  if L then
    --@localization(locale="frFR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "deDE");

  if L then
    --@localization(locale="deDE", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "esES");
  
  if L then
    --@localization(locale="esES", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "esMX");

  if L then
    --@localization(locale="esMX", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "ptBR");

  if L then
    --@localization(locale="ptBR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end


do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "koKR");

  if L then
    --@localization(locale="koKR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhCN");

  if L then
    --@localization(locale="zhCN", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhTW");

  if L then
    --@localization(locale="zhTW", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "ruRU");

  if L then
    --@localization(locale="ruRU", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "itIT");


  if L then
    --@localization(locale="itIT", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end
