-- if not L then return end

--
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating H.H.T.D.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #     HREF HERE     #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--

local _, ADDON_TABLE = ...
local ADDON_NAME = ADDON_TABLE.AddonName

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'enUS', true, true)

    if L then
      L[' %s. Type %s to see all chat commands. Have a nice game! :)'] = true
      L[' or '] = true
      L['%sDrag%s to move icon'] = true
      L['%sLeft-click%s to manualy select tracking spell'] = true
      L['%sRight-click%s to cancel current tracking spell'] = true
      L['%sShift+Left-click%s to enable/disable auto switching'] = true
      L['%sShift+Right-click%s to open settings'] = true
      L['addon is [%s]'] = true
      L['Arguments to %s :'] = true
      L['Auto tracking'] = true
      L['Cast interval'] = true
      L['Change addon icon scale'] = true
      L['Check if you want to hide default minimap tracking icon'] = true
      L['Check to hide addon minimap icon'] = true
      L['Current tracking spell'] = true
      L['Default'] = true
      L['Disable addon'] = true
      L['disabled'] = true
      L['Enable addon'] = true
      L['Enable to track only while character is moving'] = true
      L['Enable/disable addon'] = true
      L['Enable/disable only while moving mode'] = true
      L['enabled'] = true
      L['Enabled'] = true
      L['Hide addon icon'] = true
      L['Hide default tracking icon'] = true
      L['Icon display mode'] = true
      L['Icon scale'] = true
      L['Minimap'] = true
      L['Mute spell use sound'] = true
      L['Mute spell use sound is [%s]'] = true
      L['Mute spell use sound while auto switching'] = true
      L['Next tracking spell'] = true
      L['Only while moving is [%s]'] = true
      L['Only while moving'] = true
      L['Open settings'] = true
      L['paused'] = true
      L['Reset settings to defaults'] = true
      L['Reset'] = true
      L['Resources'] = true
      L['Select to include in auto tracking'] = true
      L['Select what to display inside icon'] = true
      L['Settings was reset to defaults'] = true
      L['Show this description'] = true
      L['Time in seconds between spell casts while auto tracking'] = true
      L['Toggle the addon'] = true
      L['Tracking spells'] = true
      L['Units'] = true
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'frFR');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'deDE');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'esES');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'esMX');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'koKR');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'zhCN');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'zhTW');

    if L then
      -- LOCALE
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'ruRU');

    if L then
      L[' %s. Type %s to see all chat commands. Have a nice game! :)'] = ' %s. Введите %s чтобы увидеть все команды чата. Приятной игры! :)'
      L[' or '] = ' или '
      L['%sDrag%s to move icon'] = '%sПотяните%s чтобы сдвинуть иконку'
      L['%sLeft-click%s to manualy select tracking spell'] = '%sЛКМ%s вручную выбрать способность для отслеживания'
      L['%sRight-click%s to cancel current tracking spell'] = '%sПКМ%s отменить текущую способность'
      L['%sShift+Left-click%s to enable/disable auto switching'] = '%sШифт+ЛКМ%s включить/выключить автоматическое переключение'
      L['%sShift+Right-click%s to open settings'] = '%sШифт+ПКМ%s открыть настройки'
      L['addon is [%s]'] = 'аддон [%s]'
      L['Arguments to %s :'] = 'Аргументы к %s :'
      L['Auto tracking'] = 'Автоматическое отслеживание'
      L['Cast interval'] = 'Интервал применения способности'
      L['Change addon icon scale'] = 'Изменить размеры иконки аддона'
      L['Check if you want to hide default minimap tracking icon'] = 'Отметьте если хотите скрыть стандартную иконку отслеживания на миникарте'
      L['Check to hide addon minimap icon'] = 'Отметьте если хотите скрыть иконку аддона на миникарте'
      L['Current tracking spell'] = 'Текущая способность отслеживания'
      L['Default'] = 'По умолчанию'
      L['Disable addon'] = 'Отключить аддон'
      L['disabled'] = 'выключен'
      L['Enable addon'] = 'Включить аддон'
      L['Enable to track only while character is moving'] = 'Включите чтобы отслеживать только когда персонаж движется'
      L['Enable/disable addon'] = 'Включить/выключить аддон'
      L['Enable/disable only while moving mode'] = 'Включить/выключить режим отслеживания только в движении'
      L['enabled'] = 'включен'
      L['Enabled'] = 'Включен'
      L['Hide addon icon'] = 'Скрыть иконку аддона'
      L['Hide default tracking icon'] = 'Скрыть стандартную иконку отслеживания'
      L['Icon display mode'] = 'Режим отображения иконки'
      L['Icon scale'] = 'Размеры иконки'
      L['Minimap'] = 'Миникарта'
      L['Mute spell use sound'] = 'Заглушить звук использования заклинания'
      L['Mute spell use sound is [%s]'] = 'Заглушить звук использования заклинания [%s]'
      L['Mute spell use sound while auto switching'] = 'Заглушить звук использования заклинания во время авто переключения'
      L['Next tracking spell'] = 'Следующая способность отслеживания'
      L['Only while moving is [%s]'] = 'Только в движении [%s]'
      L['Only while moving'] = 'Только в движении'
      L['Open settings'] = 'Открыть настройки'
      L['paused'] = 'пауза'
      L['Reset settings to defaults'] = 'Сбросить настройки на значения по умолчанию'
      L['Reset'] = 'Сбросить'
      L['Resources'] = 'Ресурсы'
      L['Select to include in auto tracking'] = 'Выберите чтобы включить в автоматическое отслеживание'
      L['Select what to display inside icon'] = 'Выберите что отображать внутри иконки'
      L['Settings was reset to defaults'] = 'Настройки были сброшены на значения по умолчанию'
      L['Show this description'] = 'Отобразить это описание'
      L['Time in seconds between spell casts while auto tracking'] = 'Время в секундах между применением способности во время автоматического отслеживания'
      L['Toggle the addon'] = 'Включить/выключить аддон'
      L['Tracking spells'] = 'Способности отслеживания'
      L['Units'] = 'Юниты'
    end
end

do
    local L = LibStub('AceLocale-3.0'):NewLocale(ADDON_NAME, 'itIT');

    if L then
      -- LOCALE
    end
end
