--
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Track Everything
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #  https://www.curseforge.com/wow/addons/track-everything/localization   #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--

local _, ADDON_TABLE = ...
local ADDON_NAME = ADDON_TABLE.ADDON_NAME

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "enUS", true, true)

  if L then
    --@localization(locale="enUS", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "frFR");
  
  if L then
    --@localization(locale="frFR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "deDE");

  if L then
    --@localization(locale="deDE", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "esES");
  
  if L then
    --@localization(locale="esES", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "esMX");

  if L then
    --@localization(locale="esMX", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "ptBR");

  if L then
    --@localization(locale="ptBR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end


do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "koKR");

  if L then
    --@localization(locale="koKR", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhCN");

  if L then
    --@localization(locale="zhCN", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhTW");

  if L then
    --@localization(locale="zhTW", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "ruRU");

  if L then
    --@localization(locale="ruRU", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end

do
  local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "itIT");


  if L then
    --@localization(locale="itIT", format="lua_additive_table", same-key-is-true=true, handle-subnamespaces="concat")@
  end
end
